# action.yml
name: 'No Deploy On Friday.'
description: 'This action aims to codify the unwritten rules like "No Deployments on Friday".'
inputs:
  NO_DEPLOYMENT_DAYS:
    description: A comma delimited list of weekdays that we do not deploy on. Defaults to `"Friday, Saturday, Sunday"`.
    required: false
    default: 'FRIDAY, SATURDAY, SUNDAY'
  TZ:
    description: 'The timezone name. See Wikipedia for the complete list of timezone names: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones. Defaults to `UTC`.'
    required: false
    default: 'UTC'
  COUNTRY:
    description: 'The country of origin. This determines which the national holiday calendar to use. Defaults to "`US`"'
    required: false
    default: 'US'
  HOLIDAYS:
    description: Whether to prevent deployments on national holidays. This is applied in addition to the "`NO_DEPLOYMENT_DAYS`" input. Defaults to "`true`"
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DAYS: ${{ inputs.days }}
    TIMEZOME: ${{ inputs.timezome }}
    COUNTRY: ${{ inputs.country }}
    HOLIDAYS: ${{ inputs.holidays }}
    ONLY_BEFORE_MONDAY_HOLIDAY: ${{ inputs.ONLY_BEFORE_MONDAY_HOLIDAY }}
branding:
  icon: alert-octagon
  color: red