name: End2End
on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Weekend Saver
        uses: aws-actions/no-deploy-on-friday@v0.1.0
        id: weekend-saver
        env:
          NO_DEPLOYMENT_DAYS: 'Friday, Saturday, Sunday'
          TZ: 'MST'
          COUNTRY: 'US'
          HOLIDAYS: true
      - name: Get the output reason
        if: always()
        run: echo "${{ steps.weekend-saver.outputs.reason }}"
      - name: Mock Deployment
        run: echo "Deploy something here..."