name: End2End
on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: No Deployments on Friday
        uses: aws-actions/no-deploys-on-friday@v0.1.0
        id: no-deployment-on-friday
        env:
          NO_DEPLOYMENT_DAYS: 'Friday, Saturday, Sunday'
          TZ: 'MST'
          COUNTRY: 'US'
          HOLIDAYS: true
      - name: Get the output reason
        if: always()
        run: echo "${{ steps.no-deployment-on-friday.outputs.reason }}"
      - name: Mock Deployment
        run: echo "Deploy something here..."