on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Black
        run: pip install black
      - name: Lint python with Black
        run: black --line-length 100 --check src/app