on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install python requirements
        run: |
          ls -lah
          pip install -r requirements.txt
      - name: Run python unittests
        run: python src/app/tests.py